[package]
name = "abyss_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "abyss_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module",  "abi3-py310", "generate-import-lib"] }
abyss_ir = { path = "../../../compiler/abyss_ir" }
abyss_vm = { path = "../../../compiler/abyss_vm" }
abyss_script = { path = "../../" }
