[workspace]
resolver = "2"
members = [
    # "compiler/abyss_parser",
    # "compiler/abyss_codegen",
    # "compiler/abyss_analyzer",
    # "compiler/abyss_diagnostics",
    # "compiler/abyss_vm",
    # "compiler/abyss_ir",
    # "compiler/abyss_types",
    # "compiler/abyss_utils",
    # "abyss_script",
    # "abyss_script/bindings/python",
    # "abyss_script/bindings/js",
    "compiler/abyss_nexus",
    # "compiler/abyss_hir",
    # "compiler/abyss_typer",
    # "compiler/abyss_lower",
    "compiler/abyss_lexer",
    "compiler/abyss_token",
    "compiler/abyss_parser",
]


[package]
name = "abyss"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# default = ["llvm"]
# llvm = ["dep:inkwell",
#     "dep:abyss_codegen",
#     "abyss_vm/ffi",
# ]

[dependencies]
abyss_lexer = { path = "./compiler/abyss_lexer" }
abyss_parser = { path = "./compiler/abyss_parser" }
# abyss_codegen = { path = "./compiler/abyss_codegen", optional = true }
# abyss_analyzer = { path = "./compiler/abyss_analyzer" }
# abyss_diagnostics = { path = "./compiler/abyss_diagnostics" }
# abyss_vm = { path = "./compiler/abyss_vm", default-features = false }
# abyss_ir = { path = "./compiler/abyss_ir" }
# abyss_types = { path = "./compiler/abyss_types" }
# abyss_utils = { path = "./compiler/abyss_utils" }
# abyss_hir = { path = "./compiler/abyss_hir" }
abyss_nexus = { path = "./compiler/abyss_nexus" }
# abyss_typer = { path = "./compiler/abyss_typer" }
# abyss_lower = { path = "./compiler/abyss_lower" }
#
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm21-1"], optional = true }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
