#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

void print(const unsigned char* data) {
    if (!data) return;

    while (*data) {
         putchar((char)*data);
        data++;
    }
}

void print_i64(long long x) {
    printf("%lld", x);
}

void print_f64(double x) {
    printf("%g", x);
}



// --- Generated by Abyss CTarget ---

int main(void);
// Function Definition: main
int main(void) {
    long long i = 0;
    goto label_0;
label_0:;
    if ((i < 10)) goto label_1; else goto label_2;
label_1:;
    print((unsigned char[]){ 116, 101, 115, 116, 10, 0 });
    *(&i) = (i + 1);
    goto label_0;
label_2:;
    return 0;
}

