/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_abyss_free: (a: number, b: number) => void;
export const __wbg_ctx_free: (a: number, b: number) => void;
export const __wbg_ir_free: (a: number, b: number) => void;
export const __wbg_node_free: (a: number, b: number) => void;
export const abyss_expr: (a: number, b: number, c: number, d: number, e: any) => void;
export const abyss_ident: (a: number, b: number, c: number, d: any) => void;
export const abyss_ignore: (a: number, b: number, c: number) => void;
export const abyss_new: (a: number, b: number) => number;
export const abyss_number: (a: number, b: number, c: number, d: any) => void;
export const abyss_parse: (a: number) => [number, number, number, number];
export const abyss_run: (a: number, b: any) => [number, number];
export const abyss_stmt: (a: number, b: number, c: number, d: any) => void;
export const abyss_token: (a: number, b: number, c: number, d: number, e: number) => void;
export const ctx_ident: (a: number, b: number, c: number) => [number, number, number, number];
export const ctx_node: (a: number, b: number, c: number) => [number, number, number];
export const ctx_nodes: (a: number, b: number, c: number) => [number, number, number, number];
export const ir_add: (a: number, b: number) => number;
export const ir_assign: (a: number, b: number) => number;
export const ir_bool: (a: number) => number;
export const ir_call: (a: number, b: number, c: number) => number;
export const ir_div: (a: number, b: number) => number;
export const ir_eq: (a: number, b: number) => number;
export const ir_exprStmt: (a: number) => number;
export const ir_gt: (a: number, b: number) => number;
export const ir_ifStmt: (a: number, b: number, c: number, d: number, e: number) => number;
export const ir_int: (a: number) => number;
export const ir_lt: (a: number, b: number) => number;
export const ir_mul: (a: number, b: number) => number;
export const ir_neq: (a: number, b: number) => number;
export const ir_sub: (a: number, b: number) => number;
export const ir_var: (a: number, b: number) => number;
export const ir_varDecl: (a: number, b: number, c: number) => number;
export const ir_whileStmt: (a: number, b: number, c: number) => number;
export const node___stash: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
