use std::fmt::{self, Display, Formatter};

use crate::kind::TokenKind;

impl Display for TokenKind {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            TokenKind::Comment => write!(f, "Comment"),
            TokenKind::Whitespace => write!(f, "Whitespace"),
            TokenKind::Newline => write!(f, "Newline"),
            TokenKind::Ident => write!(f, "Ident"),
            TokenKind::StrLit => write!(f, "String"),
            TokenKind::CStrLit => write!(f, "CString"),
            TokenKind::CharLit => write!(f, "Char"),
            TokenKind::HexIntLit => write!(f, "HexInteger"),
            TokenKind::BinIntLit => write!(f, "BinInteger"),
            TokenKind::OctIntLit => write!(f, "OctInteger"),
            TokenKind::FloatLit => write!(f, "Float"),
            TokenKind::IntLit => write!(f, "Integer"),
            TokenKind::Const => write!(f, "'const'"),
            TokenKind::Struct => write!(f, "'struct'"),
            TokenKind::Pub => write!(f, "'pub'"),
            TokenKind::Ret => write!(f, "'ret'"),
            TokenKind::If => write!(f, "'if'"),
            TokenKind::Then => write!(f, "'then'"),
            TokenKind::Else => write!(f, "'else'"),
            TokenKind::While => write!(f, "'while'"),
            TokenKind::For => write!(f, "'for'"),
            TokenKind::Forever => write!(f, "'forever'"),
            TokenKind::Out => write!(f, "'out'"),
            TokenKind::Next => write!(f, "'next'"),
            TokenKind::In => write!(f, "'in'"),
            TokenKind::As => write!(f, "'as'"),
            TokenKind::Is => write!(f, "'is'"),
            TokenKind::And => write!(f, "'and'"),
            TokenKind::Or => write!(f, "'or'"),
            TokenKind::Not => write!(f, "'not'"),
            TokenKind::True => write!(f, "'true'"),
            TokenKind::False => write!(f, "'false'"),
            TokenKind::Size => write!(f, "'size'"),
            TokenKind::Mod => write!(f, "'mod'"),
            TokenKind::Use => write!(f, "'use'"),
            TokenKind::Match => write!(f, "'match'"),
            TokenKind::Cmpt => write!(f, "'cmpt'"),
            TokenKind::Def => write!(f, "'def'"),
            TokenKind::Plus => write!(f, "'+'"),
            TokenKind::Minus => write!(f, "'-'"),
            TokenKind::Star => write!(f, "'*'"),
            TokenKind::Slash => write!(f, "'/'"),
            TokenKind::Percent => write!(f, "'%'"),
            TokenKind::Amp => write!(f, "'&'"),
            TokenKind::Pipe => write!(f, "'|'"),
            TokenKind::Caret => write!(f, "'^'"),
            TokenKind::LeftShift => write!(f, "'<<'"),
            TokenKind::RightShift => write!(f, "'>>'"),
            TokenKind::Tilde => write!(f, "'~'"),
            TokenKind::Comma => write!(f, "','"),
            TokenKind::Colon => write!(f, "':'"),
            TokenKind::ColonColon => write!(f, " '::'"),
            TokenKind::Semi => write!(f, "';'"),
            TokenKind::Dot => write!(f, "'.'"),
            TokenKind::DotDot => write!(f, "'..'"),
            TokenKind::OParen => write!(f, "'('"),
            TokenKind::CParen => write!(f, "')'"),
            TokenKind::OBrace => write!(f, "'{{'"),
            TokenKind::CBrace => write!(f, "'}}'"),
            TokenKind::OBracket => write!(f, "'['"),
            TokenKind::CBracket => write!(f, "']'"),
            TokenKind::Assign => write!(f, "'='"),
            TokenKind::ColonEq => write!(f, "':='"),
            TokenKind::PlusAssign => write!(f, "'+='"),
            TokenKind::MinusAssign => write!(f, "'-='"),
            TokenKind::StarAssign => write!(f, "'*='"),
            TokenKind::SlashAssign => write!(f, "'/='"),
            TokenKind::PercentAssign => write!(f, "'%='"),
            TokenKind::CaretAssign => write!(f, "'^='"),
            TokenKind::AmpAssign => write!(f, "'&='"),
            TokenKind::PipeAssign => write!(f, "'|='"),
            TokenKind::RightShiftAssign => write!(f, "'>>='"),
            TokenKind::LeftShiftAssign => write!(f, "'<<='"),
            TokenKind::EqEq => write!(f, "'=='"),
            TokenKind::BangEq => write!(f, "'!='"),
            TokenKind::Lt => write!(f, "'<'"),
            TokenKind::LtEq => write!(f, "'<='"),
            TokenKind::Gt => write!(f, "'>'"),
            TokenKind::GtEq => write!(f, "'>='"),
            TokenKind::RArrow => write!(f, "'->'"),
            TokenKind::REqArrow => write!(f, "'=>'"),
            TokenKind::Hash => write!(f, "'#'"),
            TokenKind::Underscore => write!(f, "'_'"),
            TokenKind::Unknown => write!(f, "Unknown"),
            TokenKind::Eof => write!(f, "Eof"),
        }
    }
}
