[workspace]
resolver = "2"
members = [
    "compiler/*",
]

[package]
name = "abyss"
version = "0.1.0"
edition = "2024"

[dependencies]
abyss_lexer = { path = "./compiler/abyss_lexer" }
abyss_parser = { path = "./compiler/abyss_parser" }
abyss_nexus = { path = "./compiler/abyss_nexus" }
abyss_typer = { path = "./compiler/abyss_typer" }
abyss_diagnostics = { path = "./compiler/abyss_diagnostics" }
abyss_indexer = { path = "./compiler/abyss_indexer" }
abyss_lower = { path = "./compiler/abyss_lower" }
abyss_engine = { path = "./compiler/abyss_engine" }
color-eyre = "0.6.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
