[package]
name = "abyss_nexus"
version = "0.1.0"
edition = "2024"

[dependencies]
abyss_diagnostics = { path = "../abyss_diagnostics" }
abyss_hir = { path = "../abyss_hir" }
abyss_lexer = { path = "../abyss_lexer" }
abyss_token = { path = "../abyss_token" }
abyss_types = { path = "../abyss_types" }
